### PR TITLE
Add Python3 support

### PR DESCRIPTION
**Pull request by weiwu-sre**

### CODE REVIEW

**Comment by weiwu-sre** [comment]
Should able to fix this issue.

https://github.com/UnderGreen/ansible-role-mongodb/issues/180

**Comment by smutel** [comment]
Hello,

Could we merge this MR please ?

Thanks.

**Comment by UnderGreen** [comment]
I will take a look why here is not testing for PR.

**Comment by UnderGreen** [comment]
@tomscholz and @weiwu-sre I appreciate your work and activity on this repository.
Closing this one in favor of #247.

**Pull request closed without merging**
