### PR TITLE
Fix log permissions

### PR DESCRIPTION
**Pull request by MemberIT**
Fix issue https://github.com/UnderGreen/ansible-role-mongodb/issues/192

### CODE REVIEW

**Comment by UnderGreen** [comment]
Hi @MemberIT.
I wonder if you can include mitogen changes and how it could improve build time. What do you think?

**Comment by MemberIT** [comment]
> Hi @MemberIT.
> I wonder if you can include mitogen changes and how it could improve build time. What do you think?

It seems that this really speeds up the tests if the conditions for running the tests are the same.
Without mitogen and pipelining:
https://travis-ci.org/UnderGreen/ansible-role-mongodb/builds/624985464
With mitogen and pipelining:
https://travis-ci.org/sportsru/ansible-role-mongodb/builds/625016068

https://github.com/sportsru/ansible-role-mongodb/commit/f6c591d458f1d4ccffc1bf2ceacd6600f44df0b7#diff-b5f48c5bdf0ae8ba67bb4344cd4e0366

But mitogen really speeds up ansible on multicore systems.

Can I make a separate request to make these changes?

**Comment by UnderGreen** [comment]
Looking at the total time I am a bit puzzled. What is total time and run for?
8/10 hours for whole tests for all cases? That is insane :(
I am not working with Ansible last few years and have no idea about current trends in CI. Maybe you know how to improve it and change CI?

**Comment by UnderGreen** [comment]
Ok, I got it. Real time is `Ran for XXXX`. So, mitogen improves run time from 2+ hours to 50 minutes. Absolutely worth to use it.

**Comment by MemberIT** [comment]
> Ok, I got it. Real time is `Ran for XXXX`. So, mitogen improves run time from 2+ hours to 50 minutes. Absolutely worth to use it.

Over the next week, I will create a PR to improve the performance of the tests. I have some more ideas about this.

**Pull request merged**
