### PR TITLE
Add support for MongoDB v4.0

### PR DESCRIPTION
**Pull request by ftx**

### CODE REVIEW

**Comment by dinony** [comment]
Thanks @ftx for the work!

**Comment by UnderGreen** [comment]
@ftx yes. Without travis test I can't say it is good to merge or not.

**Comment by ftx** [comment]
@UnderGreen Timeout on mongo-3, maybe you have any ideas for what? 🤔

**Comment by boutetnico** [comment]
Can this be reviewed? 4.0 has been around for some time now, it would be nice for this role to support it.

**Comment by eal** [comment]
This seems relevant:
> Starting in MongoDB 4.0, you cannot specify --nojournal option or storage.journal.enabled: false for replica set members that use the WiredTiger storage engine.

mongo3 has `mongodb_storage_journal_enabled: false` in host_vars.
Changing that variable made the tests pass for me (for DISTRIBUTION=centos DIST_VERSION=7-builded MONGODB_VERSION=4.0)

**Comment by rbjorklin** [comment]
I'm also interested in seeing this merged. @ftx do you have time to test the fix proposed by @eal?

**Comment by fllaca** [comment]
@rbjorklin I've continued @ftx work in https://github.com/UnderGreen/ansible-role-mongodb/pull/155, following @eal suggestions.

**Pull request merged**
