### PR TITLE
Redhat support

### PR DESCRIPTION
**Pull request by justinsaliba**

### CODE REVIEW

**Comment by UnderGreen** [comment]
@justinsaliba at first, thanks for the PR! But, build failed. Can you look at error and fix it.

**Comment by justinsaliba** [comment]
Hi @UnderGreen. Builds are now passing :). Don't accept the PR just yet though ... I just noticed that the MMS feature uses the `deb` task which does not work on RHEL. I'm going to close this PR and reopen (probably some time this week) once it has been fixed.

**Comment by justinsaliba** [comment]
Hi @UnderGreen. I added the EPEL installation step to the RedHat YML file, and RHEL OSes now use yum to install the correct RPM. I also added some tests for Mongo 3.4 running on Ubuntu 12.04 and 14.04 for good measure :).

**Comment by justinsaliba** [comment]
@UnderGreen two tests seemed to have failed whilst creating the symlink ... which is strange since the other tests are all using the same travis yml file. Could you try and rerun the two tests please?

**Pull request merged**
